---
# tasks file for role-jenkins
   - name: Install repository for Jenkins
     get_url: url=https://pkg.jenkins.io/redhat-stable/jenkins.repo
              dest=/etc/yum.repos.d/jenkins.repo
              mode=0440

   - name: Import Key from Jenkins Repo
     rpm_key: state=present
              key=https://pkg.jenkins.io/redhat-stable/jenkins.io.key

   - name: Install Jenkins
     yum: name=jenkins
          state=latest

   - name: Deploy Jenkins on Tomcat
     copy: remote_src=True
           src=/usr/lib/jenkins/jenkins.war
           dest=/var/lib/tomcat/webapps/
           owner=root
           group=root
#   - name: Install Jenkings plugin
#     jenkins_plugin: name=ant
#                     state=latest
#   - name: Check if we're using a password file for authentication
#     shell: cat /usr/share/tomcat/.jenkins/secrets/initialAdminPassword
#     register: adminpasswordfile

#   - name: Debug vars
#     debug: 
#       var=adminpasswordfile.stdout

   - name: Install Plugin using password
     command: >
       java -jar /var/lib/tomcat/webapps/jenkins/WEB-INF/jenkins-cli.jar -s http://localhost:8080/jenkins/
       install-plugin {{ item }} 
       --username admin
       --password-file /usr/share/tomcat/.jenkins/secrets/initialAdminPassword
     with_items: "{{ jenkins_plugins }}"

    
#   - name: Erase 'Unlock Jenkins' window
#     command: mv /usr/share/tomcat/.jenkins/secrets/initialAdminPassword /usr/share/tomcat/.jenkins/secrets/root_pass
     notify: Restart jenkins
