---
# tasks file for role-jenkins
   - name: Install Apache Server
     yum: name=httpd
          state=latest

   - name: Start Apache Server
     service: name=httpd
              state=started
              enabled=yes

   - name: Install Tomcat
     yum: name={{item}}
          state=latest
     with_items:
        - tomcat-admin-webapps
        - tomcat-webapps.noarch
        - tomcat-el-2.2-api.noarch

   - name: Start Tomcat Service
     service: name=tomcat
              state=started
              enabled=yes

          
